package EstudianteApp;


/**
* EstudianteApp/EstudiantePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estudiante.idl
* martes 21 de mayo de 2019 10:49:24 PM COT
*/

public abstract class EstudiantePOA extends org.omg.PortableServer.Servant
 implements EstudianteApp.EstudianteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEstudiante", new java.lang.Integer (0));
    _methods.put ("actualizarEstudiante", new java.lang.Integer (1));
    _methods.put ("eliminarEstudiante", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EstudianteApp/Estudiante/insertarEstudiante
       {
         int id_estudiante = in.read_long ();
         String est_nombre = in.read_wstring ();
         String est_apellido = in.read_wstring ();
         String est_fec_nacimiento = in.read_wstring ();
         int est_carrera = in.read_long ();
         boolean $result = false;
         $result = this.insertarEstudiante (id_estudiante, est_nombre, est_apellido, est_fec_nacimiento, est_carrera);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // EstudianteApp/Estudiante/actualizarEstudiante
       {
         int id_estudiante = in.read_long ();
         String este_nombre = in.read_wstring ();
         String est_apellido = in.read_wstring ();
         String est_fecha_nacimiento = in.read_wstring ();
         int est_carrera = in.read_long ();
         boolean $result = false;
         $result = this.actualizarEstudiante (id_estudiante, este_nombre, est_apellido, est_fecha_nacimiento, est_carrera);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // EstudianteApp/Estudiante/eliminarEstudiante
       {
         int id_estudiante = in.read_long ();
         boolean $result = false;
         $result = this.eliminarEstudiante (id_estudiante);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // EstudianteApp/Estudiante/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EstudianteApp/Estudiante:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Estudiante _this() 
  {
    return EstudianteHelper.narrow(
    super._this_object());
  }

  public Estudiante _this(org.omg.CORBA.ORB orb) 
  {
    return EstudianteHelper.narrow(
    super._this_object(orb));
  }


} // class EstudiantePOA
