package EstudianteApp;


/**
* EstudianteApp/Estudiante.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estudiante.idl
* martes 21 de mayo de 2019 10:49:24 PM COT
*/

public interface Estudiante extends EstudianteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Estudiante
