/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estudiante;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cadefihuilaltda
 */
public class EstudianteFRM extends javax.swing.JFrame {

    /**
     * Creates new form CaficultorFRM
     */
    private DefaultTableModel modeloTablaEstudiante;
    public EstudianteFRM() {
        modeloTablaEstudiante = new DefaultTableModel(null, getColumn());
        initComponents();
        cargarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String[] getColumn(){
        String columnas[] = new String[]{"Codigo", "Nombres","Apellidos", "Fecha de Nacimiento","Carrera"};
        return columnas;
    }
    
    private void cargarTabla(){
        Estudiante objPersona = new Estudiante();
        ResultSet resultado = objPersona.cargarTablaEstudiante();
        try{
            Object dato[] = new Object[10];
            while(resultado.next()){
                for(int i = 0; i < 10;i++){
                dato[i] = resultado.getObject(i+1);
                }
            modeloTablaEstudiante.addRow(dato);
            }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Ocurrio un error: "+ex.getMessage());
        }
    }
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbid_estudiante = new javax.swing.JLabel();
        lbl_est_nombre = new javax.swing.JLabel();
        lbl_est_apellido = new javax.swing.JLabel();
        lbl_est_fec_nacimiento = new javax.swing.JLabel();
        lbl_est_carrera = new javax.swing.JLabel();
        txt_id_estudiante = new javax.swing.JTextField();
        txt_est_nombre = new javax.swing.JTextField();
        txt_est_apellido = new javax.swing.JTextField();
        txt_est_fec_nacimiento = new javax.swing.JTextField();
        txt_est_carrera = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_alumno = new javax.swing.JTable();
        estudiante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbid_estudiante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbid_estudiante.setText("Codigo:");

        lbl_est_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_est_nombre.setText("Nombres Estudiante:");

        lbl_est_apellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_est_apellido.setText("Apellidos Estudiante:");

        lbl_est_fec_nacimiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_est_fec_nacimiento.setText("Fecha de Nacimiento:");

        lbl_est_carrera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_est_carrera.setText("Carrera:");

        txt_id_estudiante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_id_estudiante.setForeground(new java.awt.Color(0, 0, 153));

        txt_est_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_est_nombre.setForeground(new java.awt.Color(0, 0, 153));

        txt_est_apellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_est_apellido.setForeground(new java.awt.Color(0, 0, 153));

        txt_est_fec_nacimiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_est_fec_nacimiento.setForeground(new java.awt.Color(0, 0, 153));

        txt_est_carrera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_est_carrera.setForeground(new java.awt.Color(0, 0, 153));

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(153, 0, 0));
        btnEliminar.setText("Eliminar");

        jtb_alumno.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtb_alumno.setForeground(new java.awt.Color(0, 0, 102));
        jtb_alumno.setModel(modeloTablaEstudiante);
        jScrollPane1.setViewportView(jtb_alumno);

        estudiante.setBackground(new java.awt.Color(0, 102, 102));
        estudiante.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        estudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estudiante.setText("Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbid_estudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_est_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(lbl_est_apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_est_carrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_est_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_est_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_est_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_id_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_est_fec_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(txt_est_fec_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(estudiante)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbid_estudiante)
                            .addComponent(txt_id_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_est_nombre)
                            .addComponent(txt_est_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_est_apellido)
                            .addComponent(txt_est_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_est_fec_nacimiento)
                            .addComponent(txt_est_fec_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_est_carrera)
                            .addComponent(txt_est_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnEliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Estudiante objEstudiante = new Estudiante();
        int id_estudiante =  Integer.parseInt(txt_id_estudiante.getText());
     
        String est_nombre = txt_est_nombre.getText();
        String est_apellido = txt_est_apellido.getText();
     
        String est_fec_nacimiento = txt_est_fec_nacimiento.getText();
     
        int est_carrera = Integer.parseInt(txt_est_carrera.getText());
       

        
        boolean resultado = objEstudiante.insertarEstudiante(id_estudiante,est_nombre,est_apellido,est_fec_nacimiento,est_carrera);
        if(resultado){
            JOptionPane.showMessageDialog(null, "Se inserto correctamente.");
            modeloTablaEstudiante.setRowCount(0);
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrio un error al insertar.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel estudiante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb_alumno;
    private javax.swing.JLabel lbid_estudiante;
    private javax.swing.JLabel lbl_est_apellido;
    private javax.swing.JLabel lbl_est_carrera;
    private javax.swing.JLabel lbl_est_fec_nacimiento;
    private javax.swing.JLabel lbl_est_nombre;
    private javax.swing.JTextField txt_est_apellido;
    private javax.swing.JTextField txt_est_carrera;
    private javax.swing.JTextField txt_est_fec_nacimiento;
    private javax.swing.JTextField txt_est_nombre;
    private javax.swing.JTextField txt_id_estudiante;
    // End of variables declaration//GEN-END:variables
}
